### ISSUE TITLE
Telegram channel limit. Multichannels?

### ISSUE THREAD

**Issue by Xabiman** [divyam234/teldrive#255]
Telegram has a limit, it's not possible to read more than 1000000 messages per channel, and Teldrive can't access to older files than 1000000. Is it possible to use more than one channel to the same Teldrive? How to do this if possible?

**Comment by NiTr0gLiTcH** [comment]
were you able to reach 1mln messages in a single channel?
i knew this issue existed years ago, but i thought it was solved already.

**Comment by Xabiman** [comment]
Yes, uploading 1M files is possible... And the issue is not solved unfortunately. So, is there any way to use more than 1 channel to upload files with Teldrive?

**Comment by NiTr0gLiTcH** [comment]
just create another channel and select it from the gui.

btw what i was asking is if you reached 1mln on teldrive, tried to request the first files you uploaded and it gave you some kind of error.
if you did, could you share your log?

**Comment by Imaje3d** [comment]
this is the error when run teldrive comand:
ERROR   Ignored key without a value.    {"ignored": null}
10/06/2024 12:24 PM     ERROR   failed to delete messages

And this is the error when try to play/download any video or archive:


2024/06/10 12:36:47 [Recovery] 2024/06/10 - 12:36:47 panic recovered:
interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message
runtime/iface.go:262 (0x40ecb0)
runtime/iface.go:272 (0x40ec69)
github.com/divyam234/teldrive/pkg/services/common.go:229 (0x15821dd)
github.com/divyam234/teldrive/pkg/services/file.go:643 (0x1589cb5)
github.com/divyam234/teldrive/pkg/controller/file.go:196 (0x1596248)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1631c82)
github.com/divyam234/teldrive/cmd/run.go:233 (0x1631c70)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x9890aa)
github.com/gin-contrib/zap@v1.1.3/zap.go:68 (0x1630e30)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x996539)
github.com/gin-gonic/gin@v1.10.0/recovery.go:102 (0x996527)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x9952d1)
github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0x994d40)
github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0x994871)
net/http/server.go:3137 (0x77a22d)
net/http/server.go:2039 (0x7755e7)
runtime/asm_amd64.s:1695 (0x471920)

**Comment by NiTr0gLiTcH** [comment]
did you manually check if the file is really on telegram or it's just a ghost entry?
some months ago it used to happen from time to time that a file part would be deleted from chat during up, but the entry would still be added to the database.

**Comment by Xabiman** [comment]
I've checked that all the files before a date have disappeared because the channel have more than 1M files.

@NiTr0gLiTcH When you say I can select another different channel from the gui, then the new files added from this moment will be uploaded to this new channel and Teldrive will know what channel is used to every file. Is this correct? Then I can use multiple channels... Is it ok?

**Comment by steffen-poulsen** [comment]
For reference, I hit the same 1000000 file limit in https://github.com/divyam234/teldrive/issues/242. https://github.com/divyam234/teldrive/issues/254 could be releated also.

> @NiTr0gLiTcH When you say I can select another different channel from the gui, then the new files added from this moment will be uploaded to this new channel and Teldrive will know what channel is used to every file. Is this correct? Then I can use multiple channels... Is it ok?

Yes, you are right, every entry in the files table in the database is marked up with the id of the telegram channel it belongs to.

If you upload through the gui, all files will go to the new default channel instantly.

If you upload through rclone, make sure that the config file does not have an explicit "channel_id" configuration setting, or else files will still go to this configured channel. You can just delete the setting from the rclone.conf file if you want to go with the default channel for rclone uploads also.

**Comment by divyam234** [comment]
Do you realize how much you have abused the service by saving close to half a petabyte of data just for movies and TV shows? Instead of using something like Stremio with debrid , everyone seems to want to create their own Netflix without understanding the negative impact it causes. Many people use this service fairly, but a few individuals are ruining the entire experience for everyone. These are often the same people who ask for feature requests without ever donating to the project, always looking for a free lunch.

**Comment by Xabiman** [comment]
> Do you realize how much you have abused the service by saving close to half a petabyte of data just for movies and TV shows? Instead of using something like Stremio with debrid , everyone seems to want to create their own Netflix without understanding the negative impact it causes. Many people use this service fairly, but a few individuals are ruining the entire experience for everyone. These are often the same people who ask for feature requests without ever donating to the project, always looking for a free lunch.

@divyam234  First of all thanks for the great work.  I don't collect movies to have my Netflix, I have thousands of files from my work and my hobby in musical shows, theater and television, photos, videos (I work in video editing), musical scores, index cards... most of them don't take up much space but it is a very large number of files.  In addition to some old movies and series and special collector's editions that are difficult to find online.  By my mistake I have uploaded a large part of this duplicate content on the same channel and it has caused my database and my Telegram channel to fill up, I am trying to clean it, but if I don't succeed I will have to directly delete the entire channel and go back to start from the beginning, even if it takes me months.  Sorry for the misunderstanding and thanks again for the work.  By the way, I did make a modest donation to the project.

**Comment by divyam234** [comment]
@Xabiman I am  pointing to you specifically  I am just pointing out to people who uses  plex, emby etc to save content in 4k HDR mainly  even if there are better alternatives avaliable like  x265  encodes or streamio  because of these people only  storage providers are revising their plans and they are now abusing telegram servers but will eventually affect teldrive.

**Comment by steffen-poulsen** [comment]
Yes, that appears to be the way of it so far, [this rclone thread as a worthy journal](https://forum.rclone.org/t/unlimited-alternatives-to-google-drive-what-are-the-options/36529). Any free or just cheap-enough service is bound to be abused. Seeing how for instance the DropBox Business Advanced offer was only able to sustain itself for a couple of weeks before it had been abused to death was an interesting watch.

The Telegram case is special because it is so extremely slow and unpredictable compared to other storage offerings we have seen. For instance, streaming 4K HDR content or just 1080p h264 content is simply impossible, because the bandwidth and stability is not there to support it.

As the Telegram backend cannot support Plex/Emby-as-Netflix installations, this means that the type of storage abuse is somewhat different and a lot less for this backend. Also, everybody knows that with Telegram your data could be gone in an instant, without any explanation. Meaning, your efforts could be down the drain at any given moment.

Anyway, Telegram is still just beginning its monetization journey. And Pavel Durov is still a lot more interested in user count, apps, coins, ai and freedom philosophy than he is in earning money. But once he gets ready for an IPO, I expect things to start changing fast.

So yes, of course the Telegram service and teldrive will eventually be affected. Probably the first sign will be that we will see the backend gradually reduced in speed until at last it is completely unusable. But I personally don't expect anything to change the next few years. Telegram has 2.5 million new users signing up every day, and they want to keep themselves as attractive as possible for a while still.

> ... and they are now abusing telegram servers but will eventually affect teldrive.

When you say eventually, what timeframe are you imagining? Just curious :-)
